### ISSUE TITLE
Not receiving TestPyPI verification emails

### ISSUE THREAD

**Issue by thisisazeez** [pypi/warehouse#14571]
**Describe the bug**

Hi - I'm having the same issue from #11128 and a few others I've seen. I've tried a few times to get the verification emails from test over the past two days but haven't gotten any (live PyPI goes through immediately however).

Verification emails are working properly with my [testing account at test.pypi.org](https://test.pypi.org/user/thisisazeez/), but the same setup in [my pypi.org account](https://pypi.org/user/thisisazeez/) is not working.

**Expected behavior**

Receiving a confirmation email for each address configured in my account.

**To Reproduce**

Create an account via https://pypi.org/account/register/
Go to https://pypi.org/manage/account/#account-emails and request a verification email.
The system shows a "Verification email for XXX@YYY resent" message, but no message arrives even after some hours.
Problem happens with both primary and non-primary email addresses.

**Comment by imigueldiaz** [comment]
Same problem here, I hope It's a temporary issue related to the mail server...

**Comment by thisisazeez** [comment]
Might be, for the time being i will try the main pypi to see if it works.

**Comment by thisisazeez** [comment]
Might be, for the time being i will try the main pypi to see if it works.

**Comment by bigsbug** [comment]
same here. I can't receive the verification email from test.pypi.org, I tested several emails but the result is the same

**Comment by imigueldiaz** [comment]
Mine just received and I have been able to verify (test site)

**Comment by bigsbug** [comment]
I checked now, it is fixed

**Comment by tkoukkari** [comment]
Doesn't seem to be working for me

**Comment by miketheman** [comment]
A recent change was rolled back allows all background processing jobs to run.

**Comment by systemallica** [comment]
This issue is still happening for me, I am not receiving the verification email for [my account](https://pypi.org/user/systemallica/). I have tried re-sending the email several times to no avail. I also double-checked the spam folder, but it is not there either.

Other emails (such as password reset email) seem to have reached my inbox just fine.

Any insights? @mi
